apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "helm-chart.labels" . | nindent 4 }}
    app: {{ .Values.app }}
    component: registry-secret
type: {{ .Values.secret.type }}
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJnaXRvcHNpdG1vIiwicGFzc3dvcmQiOiJkY2tyX3BhdF8zbkNWVC1FSHprVEh2RjBzNndJUlRhQmR4b28iLCJlbWFpbCI6ImdpdG9wc2l0bW9AZXhhbXBsZS5jb20iLCJhdXRoIjoiWjJsMGIzQnphWFJ0Ynpwa1kydHlYM0JoZEY4emJrTldWQzFGU0hwclZFaDJSakJ6Tm5kSlVsUmhRbVI0YjI4PSJ9fX0=
